controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - finger_joint_1
        - finger_joint_2
      state_publish_rate: 50
      action_monitor_rate: 50
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.05
        joint_1:
          trajectory: 0.1
          goal: 0.1
        joint_2:
          trajectory: 0.1
          goal: 0.1
        joint_3:
          trajectory: 0.1
          goal: 0.1
        joint_4:
          trajectory: 0.1
          goal: 0.1
        finger_joint_1:
          trajectory: 0.1
          goal: 0.1
        finger_joint_2:
          trajectory: 0.1
          goal: 0.1
      gains:
        joint_1:
          p: 100.0
          i: 1.0
          d: 10.0
        joint_2:
          p: 100.0
          i: 1.0
          d: 10.0
        joint_3:
          p: 100.0
          i: 1.0
          d: 10.0
        joint_4:
          p: 100.0
          i: 1.0
          d: 10.0
        finger_joint_1:
          p: 100.0
          i: 1.0
          d: 10.0
        finger_joint_2:
          p: 100.0
          i: 1.0
          d: 10.0
